### PR TITLE
templateDirectory should be relative to skin

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Review by HM100 — CHANGES_REQUESTED** [review]
Are you sure it will work that way? I tested that change and it caused an error

**Comment by Universal-Omega** [comment]
> Are you sure it will work that way? I tested that change and it caused an error: `` Original exception: [f7cec89d26a23f280f63352f] /wiki/index.php/Sample_Test_Page RuntimeException: Could not find template `skin` at templates/skin.mustache ``

hmm, right now it is causing a warning, or at least I think it is coming from Evelution.

**Comment by HM100** [comment]
> > Are you sure it will work that way? I tested that change and it caused an error: `` Original exception: [f7cec89d26a23f280f63352f] /wiki/index.php/Sample_Test_Page RuntimeException: Could not find template `skin` at templates/skin.mustache ``
> 
> hmm, right now it is causing a warning, or at least I think it is coming from Evelution.

It comes from Evelution so if it can't be worked that way, then this can't be merged

**Comment by Universal-Omega** [comment]
I tested this, this patch does work on 1.37 to fix warnings.

**Comment by HM100** [comment]
> I tested this, this patch does work on 1.37 to fix warnings.

Yeah but we need to support 1.36 as well :(

**Pull request closed without merging**
